### ISSUE TITLE
Browser Strategy

### ISSUE THREAD

**Issue by ChaeWonKong** [Nexters/landlords-web#96]
## Browser Strategy

카카오웹뷰로 checkhaebang을 열려고 할 경우 사용자를 강제로 크롬/사파리 등 외부 브라우저로 이동시킵니다.

### Ref
- 강제로 외부 브라우저로 연결: https://www.burndogfather.com/201
- User Agent 활용: https://naver.github.io/egjs-agent/
- React Error Boundary: https://github.com/bvaughn/react-error-boundary

**Comment by mcauto** [comment]
구글 로그인 에서 카카오 로그인으로 변경
